### ISSUE TITLE
White frame perceptual progress can be significantly greater than 0

### ISSUE THREAD

**Issue by patrickhulce** [paulirish/speedline#48]
The problem now that we're using real SSIM is that `getPerceptualProgress` normalizes the value relative to the global min instead of the SSIM of the white frame with the target frame. This creates some very unintuitive histograms based on the fact that a page with a white background can be quite structurally similar to a white frame.

A recent trace of CNN highlights this issue. Their home page loads content with header, image, and text before an ad pops in above that pushes all the content down. The frame before the ad has a structural similarity with the target of ~18% while empty white has a structural similarity of ~30% which results in the following histogram.
![image](https://cloud.githubusercontent.com/assets/2301202/25829435/eaceb848-340a-11e7-8303-b4c54337d77c.png)

This artificially deflates the perceptual speed index for credit before first paint, and does not appropriately punish the site for progressively rendering toward a target that is abruptly changed. The histogram should instead look like the following if normalized to the first frame:
![image](https://cloud.githubusercontent.com/assets/2301202/25829460/18f37c90-340b-11e7-94f9-b2b989929505.png)

| Before Ad | After Ad
|----|-----|
| ![image](https://cloud.githubusercontent.com/assets/2301202/25829384/88a9e732-340a-11e7-9dfc-a1e026391f4d.png) | ![image](https://cloud.githubusercontent.com/assets/2301202/25829391/94137b24-340a-11e7-8dc5-475609cc97c2.png) |

**Comment by pahammad** [comment]
We explicitly addressed this issue (in VisualMetrics repository) earlier by starting the pairwise frame comparison from firstPaint frame instead of time=0 (white) frame. The modified PSI equation looks like: PSI = firstPaint + sum (from firstPaint to end) {Perceptual_pairwise_FrameDifference}. This means you don't have to compute pairwise frame differences upto firstPaint. This may make the compute faster as well. In this formula, Perceptual_pairwise_FrameDifference is computed using SSIM.

**Comment by patrickhulce** [comment]
By "VisualMetrics repository" are you referring to https://github.com/WPO-Foundation/visualmetrics/blob/f846edeb39ec837d9aa183775edbfc30614d2ae6/visualmetrics.py#L1260?

**Comment by pahammad** [comment]
Yeah, this function: https://github.com/WPO-Foundation/visualmetrics/blob/f846edeb39ec837d9aa183775edbfc30614d2ae6/visualmetrics.py#L1241
