### ISSUE TITLE
Histogram shown twice

### ISSUE THREAD

**Issue by nhoizey** [paulirish/speedline#56]
I tried this tool, and it is great, thanks!

But it showed the histogram twice in my shell, I don't know why:

![image](https://user-images.githubusercontent.com/78213/30686446-97125aac-9eb8-11e7-97ba-c3aaecd0783b.png)

**Comment by soulgalore** [comment]
Hi @nhoizey the last one is for perceptual visual progress. You can checkout the talk by Estelle where she explains the difference between SpeedIndex and Perceptual SpeedIndex: https://air.mozilla.org/measuring-the-subjective-the-performance-dashboard-with-estelle-weyl/

Best
Peter

**Comment by nhoizey** [comment]
@soulgalore wow, didn't notice these are different, sorry. I will check Estelle's talk, thanks!
